// OpenTelemetry instrumentation for Axum-todo — generated by TelemetryOS.
// SLO contract v1. SLIs covered: Axum-todo — HTTP Worker Pool Saturation.
// Adapt the snippets below to your service; they are grounded scaffolds.

package telemetry

import "go.opentelemetry.io/otel"

var (
	meter  = otel.Meter("Axum-todo")
	tracer = otel.Tracer("Axum-todo")
)

// ── SLI: Axum-todo — HTTP Worker Pool Saturation (axum-todo-http-saturation) — complexity: medium ──
// Active-request and pool-size gauges
activeRequests, _ := meter.Int64ObservableGauge("http.server.active_requests")
poolSize, _ := meter.Int64ObservableGauge("http.server.worker_pool.size")

meter.RegisterCallback(func(_ context.Context, o metric.Observer) error {
  o.ObserveInt64(activeRequests, server.ActiveRequests())
  o.ObserveInt64(poolSize, int64(server.MaxWorkers()))
  return nil
}, activeRequests, poolSize)
